services:
  - type: web
    name: murf-ai-app
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: GEMINI_API_KEY
        sync: false
        generateValue: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
        generateValue: false
      - key: MURF_API_KEY
        sync: false
        generateValue: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
